add_newline = false
command_timeout = 1500

format = """(\\[$username$hostname\\] )$directory$character"""
right_format = """$git_branch$git_status$ruby$nodejs$golang"""

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "red"
read_only = " "
format = "[$path]($style)[$read_only]($read_only_style) "

[username]
style_user = "bold red"
format = "[$user]($style)@"

[hostname]
ssh_only = true
format = '[$hostname]($style)'
style = 'bold red'

[git_branch]
symbol = " "
style = "bold green"
format = "on [$symbol$branch]($style) "

[nodejs]
symbol = ""
format = "via [$symbol ($version)]($style)"

[golang]
symbol = ""

[ruby]
symbol = "\ue21e"
format = "via [$symbol ($version)]($style)"
detect_variables = []
